server:
    port: 8080
    max-http-header-size: 64kb
spring:
    profiles:
        active: ${SPRING_ACTIVE_PROFILE:dev}
    application:
        name: ofx-gateway
    cloud:
        gateway:
            httpclient:
                connect-timeout: 6000
                response-timeout: 60s
                ssl:
                    useInsecureTrustManager: true
#            globalcors:
#                cors-configurations:
#                    '[/**]':
#                        allowedOrigins: "*" #"https://localhost:3000"
#                        allowedMethods:
#                            - GET
#                            - POST
#                            - PUT
#                            - PATCH
#                            - DELETE
#                        allowedHeaders: '*'
#                        maxAge: 30
            routes:
                -   id: ofx-service-registry
                    uri: lb://ofx-service-registry
                    predicates:
                        - Path=/eureka/**
                    filters:
                        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

                -   id: ofx-ms-import
                    uri: lb://ofx-ms-import
                    predicates:
                        - Path=/api/v1/import/**
                    filters:
                        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

                -   id: ofx-ms-data
                    uri: lb://ofx-ms-data
                    predicates:
                        - Path=/api/v1/data/**
                    filters:
                        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

                -   id: ofx-ms-sse
                    uri: lb://ofxmssse
                    predicates:
                        - Path=/api/v1/sse/**
                    filters:
                        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

                -   id: ofx-permission-checker
                    uri: lb://ofx-permission-checker
                    predicates:
                        - Path=/api/v1/permission-checker/**
                    filters:
                        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

logging:
    level:
        root: DEBUG
        org.apache.http: DEBUG
        org.springframework.web: DEBUG
        dev.luisjohann.ofxpermissionchecker: DEBUG
        org.springframework.security: DEBUG
        org.springframework.security.oauth2: DEBUG
        org.springframework.security.web.authentication: DEBUG
        org.springframework.security.oauth2.client: DEBUG
        org.springframework.security.oauth2.jwt: DEBUG
        org.springframework.security.oauth2.server.resource: DEBUG
        org.keycloak: DEBUG
        org.keycloak.adapters: DEBUG
        org.keycloak.authentication: DEBUG
        org.keycloak.events: DEBUG
        org.springframework.web.reactive.DispatcherHandler: DEBUG
        org.springframework.web.reactive.function.client: DEBUG
        org.springframework.web.reactive.function.server: DEBUG
        org.springframework.web.filter.reactive: DEBUG