server:
    port: 8080
spring:
    profiles:
        active: ${SPRING_ACTIVE_PROFILE:dev}
    application:
        name: ofx-gateway
    cloud:
        gateway:
#            globalcors:
#                cors-configurations:
#                    '[/**]':
#                        allowedOrigins: "*" #"https://localhost:3000"
#                        allowedMethods:
#                            - GET
#                            - POST
#                            - PUT
#                            - PATCH
#                            - DELETE
#                        allowedHeaders: '*'
#                        maxAge: 30
            routes:
                -   id: ofx-service-registry
                    uri: lb://ofx-service-registry
                    predicates:
                        - Path=/eureka/**
                    filters:
                        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

                -   id: ofx-ms-import
                    uri: lb://ofx-ms-import
                    predicates:
                        - Path=/api/v1/import/**
                    filters:
                        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

                -   id: ofx-ms-data
                    uri: lb://ofx-ms-data
                    predicates:
                        - Path=/api/v1/data/**
                    filters:
                        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

                -   id: ofx-ms-sse
                    uri: lb://ofxmssse
                    predicates:
                        - Path=/api/v1/sse/**
                    filters:
                        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

                -   id: ofx-permission-checker
                    uri: lb://ofx-permission-checker
                    predicates:
                        - Path=/api/v1/permission-checker/**
                    filters:
                        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/